[package]
name = "html-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
lib-money = { path = "../lib-money" }
proc-macro2 = "1.0.101"
quote = "1.0.40"
syn = { version = "2.0.106", features = ["full"] }
